CREATE TABLE USER( 
	ID          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME	VARCHAR2(100) NOT NULL,
	PASSWORD	VARCHAR2(100) NOT NULL,
	FULL_NAME	VARCHAR2(100) NULL,
	MAIL		VARCHAR2(100) NULL,
	ROLE		VARCHAR2(100) NULL,
	AWS_KEY	VARCHAR2(200) NULL,
	AWS_SECRET_KEY	VARCHAR2(200) NULL,
	SAVE_KEYS BOOLEAN,
	EXPORT_TO_S3 BOOLEAN,
	S3_BUCKET	VARCHAR2(200) NULL,
	EXPORT_INPUT_TO_S3 BOOLEAN,
	ACTIVATION_CODE	VARCHAR2(200) NULL,
	ACTIVE BOOLEAN
);

CREATE TABLE JOB( 
	ID		VARCHAR2(100) NOT NULL PRIMARY KEY,
	STATE		INTEGER NOT NULL,
	START_TIME	BIGINT NOT NULL,
	END_TIME	BIGINT NOT NULL,
	NAME 		VARCHAR2(300),
	S3_URL		VARCHAR2(300),
	TYPE		INTEGER,
	USER_ID INTEGER NOT NULL REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE PARAMETER( 
	ID			INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME		VARCHAR2(100) NOT NULL,
	VALUE		VARCHAR2(200) NOT NULL,
	TYPE		VARCHAR2(25) NOT NULL,
	FORMAT		VARCHAR2(25) NULL,
	INPUT		BOOLEAN,
	DOWNLOAD	BOOLEAN,
	VARIABLE	VARCHAR2(100) NOT NULL,
	JOB_ID		VARCHAR2(100) NOT NULL REFERENCES JOB(ID) ON DELETE CASCADE
);

CREATE TABLE STEPS ( 
	ID	    	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATE		INTEGER NOT NULL,
	NAME	    VARCHAR2(300),
	START_TIME	BIGINT NOT NULL,
	END_TIME	BIGINT NOT NULL,
	JOB_ID		VARCHAR2(100) NOT NULL
);

CREATE TABLE LOG_MESSAGES(
 	ID			INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	TIME	    BIGINT NOT NULL,
	TYPE		INTEGER NOT NULL,
	MESSAGE	    VARCHAR2(1000),
	STEP_ID		INTEGER NOT NULL REFERENCES STEPS(ID) ON DELETE CASCADE
);

