--1.0.3
CREATE TABLE DOWNLOADS(
 	ID			  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	PARAMETER_ID  VARCHAR2(200) NOT NULL,
 	JOB_ID  VARCHAR2(100) NOT NULL,
 	NAME		  VARCHAR2(200) NULL,
 	PATH		  VARCHAR2(200) NULL,
 	HASH          VARCHAR2(200) NULL,		   
	COUNT	      INTEGER NOT NULL,
	SIZE		  VARCHAR2(200) NULL
); 

--1.0.5

CREATE TABLE CACHE_ENTRIES ( 
	ID	    	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SIGNATURE	    VARCHAR2(300),
	USED		INTEGER NOT NULL,
	LAST_USED_ON	BIGINT NOT NULL,
	CREATED_ON	BIGINT NOT NULL,
	EXECUTION_TIME	BIGINT NOT NULL,
	SIZE	        BIGINT NOT NULL,
	USER_ID		VARCHAR2(100) NULL,
	JOB_ID		VARCHAR2(100) NULL,
	OUTPUT          VARCHAR2(1000)
);

--1.0.7

CREATE TABLE COUNTERS ( 
	ID	    	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME		VARCHAR2(300),
	JOB_ID		VARCHAR2(100) NULL,
	VALUE		BIGINT NOT NULL
);


--1.9.0

CREATE TABLE COUNTERS_HISTORY ( 
	ID	    	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TIME_STAMP	BIGINT NOT NULL,
	NAME		VARCHAR2(300),
	VALUE		BIGINT NOT NULL	
);

--1.9.1

CREATE TABLE HTML_SNIPPETS ( 
	ID	    	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	KEY	     	VARCHAR2(300),
	TEXT		VARCHAR2(1000)	
);