#! /bin/bash
#  Cloudgene CLI


# The path to the folder containing MyDaemon.jar
FILE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Hadoop path with all jars
HADOOP_CLASS_PATH=``
if command -v hadoop > /dev/null 2>&1; then
  HADOOP_CLASS_PATH=`hadoop classpath`
fi

# Our classpath including our jar file
CLASS_PATH="$FILE_PATH/cloudgene.jar:$HADOOP_CLASS_PATH"

# The fully qualified name of the class to execute
CLASS="cloudgene.mapred.CommandLineInterface"

# change current directory
cd $FILE_PATH

# execute cloudgene
java -Dlog4j.configurationFile=config/log4j2.xml -cp $CLASS_PATH $CLASS "$@"
